name: Build Affected Apps and Libs
on:
  pull_request:
    branches: [main]

jobs:
  build-affected:
    runs-on: ubuntu-latest

    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/.cache
            **/.next/cache
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install pnpm
        uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.14.1

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin $GITHUB_BASE_REF

      - name: Build
        shell: bash
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export NX_BASE=remotes/origin/$GITHUB_BASE_REF
          else
            export NX_BASE=$(git rev-parse HEAD~1)
          fi
          echo "Base => $NX_BASE"
          pnpm run affected:build -- --base=$NX_BASE
